call gem install public_suffix
call gem install addressable
call gem install bundler
call gem install colorator
call gem install concurrent-ruby 
call gem install eventmachine
call gem install http_parser.rb 
call gem install em-websocket 
call gem install ffi 
call gem install forwardable-extended 
call gem install i18n 
call gem install sassc 
call gem install jekyll-sass-converter 
call gem install rb-fsevent
call gem install rb-inotify
call gem install listen 
call gem install jekyll-watch 
call gem install rexml 
call gem install kramdown 
call gem install kramdown-parser-gfm 
call gem install liquid 
call gem install mercenary 
call gem install pathutil 
call gem install rouge 
call gem install safe_yaml 
call gem install unicode-display_width 
call gem install terminal-table 
call gem install jekyll 
call gem install jekyll-feed 
call gem install jekyll-paginate 
call gem install jekyll-seo-tag 
call gem install jekyll-sitemap 
